### ISSUE TITLE
[MySQL] in v0.9.0, the server time zone error occurs

### ISSUE THREAD

**Issue by corselia** [embulk/embulk-input-jdbc#133]
### TL;DR
in `embulk-input-mysql` v0.9.0, it looks that the server time zone value is unrecognized.

#### executed command

```bash
$ embulk run config.yml
```

#### content of `config.yml`
- note: `my_table` doesn't contain column of `date` or `time` or `datetime` type 

```yaml
in:
  type: mysql
  host: 127.0.0.1
  user: username
  password: password
  database: db_name
  query: "SELECT * FROM my_table"
```

#### error message

> 2017-12-27 13:00:21.193 | org.embulk.exec.PartialExecutionException: java.lang.RuntimeException: java.sql.SQLException: The server time zone value '���� (�W����)' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.

#### I tryed
- I added `  default_timezone: Asia/Tokyo` to `config.yml`
- but the result was the same

#### note
- in v0.8.6, run correctly
- In my circumstances, I cannot modify MySQL server's timezone ;-(

thank you for great product, `embulk-input-mysql` :)
