### ISSUE TITLE
【MYSQL】date issue with 0001-01-01

### ISSUE THREAD

**Issue by gotokatsuya** [embulk/embulk-input-jdbc#157]
I create one table and test.yaml to try using embulk run.

|id|date|datetime|
|:---|:---|:---|
|1|0001-01-01|0001-01-01 00:00:00|

```
in:
  type: mysql
  host: localhost
  user: user
  password: password
  database: db
  query: |
    SELECT date,datetime FROM one WHERE id = 1

out:
  type: stdout
```

Then, use embulk run
```
$ embulk run test.yml
```

Result
```
0000-12-29,0000-12-30 00:00:00
````

I think result is not correct. Do you have any solution or idea ?
