### ISSUE TITLE
java.lang.RuntimeException: java.sql.SQLException: ORA-01555

### ISSUE THREAD

**Issue by OmkarPathak** [embulk/embulk-input-jdbc#176]
Hello team,

We are trying to load a table with size of almost 400 GB using `embulk-input-oracle` to load from Oracle DB and `embulk-output-bigquery` to load into Bigquery. We are getting below error while performing this task:

```
org.embulk.exec.PartialExecutionException: java.lang.RuntimeException: java.sql.SQLException: ORA-01555: snapshot too old: rollback segment number 61 with name "XYZ$" too small
```

Anyone has the idea of why this error is generated? Is there anything we can do to fix this?

**Comment by hiroyuki-sato** [comment]
Hello, @OmkarPathak 

Could you tell us the following?

* Operating system
* Embulk version
* Plugin version
* Configuration
* Error log detail (Full-stack trace)
* Does this error occur always or not always?

I'm not familiar `embulk-input-oracle`. It seems that the error code `ORA-01555` is related to rollback.

I think you need to minimize the problem.

* Have you ever tried output "null" plugin?, If you get the same error, It relates to the input side.
* Have you ever tried this setting? http://gallinar.blogspot.com/2014/04/ora-01555-snapshot-too-old-rollback.html 

```yaml
out:
  type: "null" # require quote
```

**Comment by OmkarPathak** [comment]
Hi @hiroyuki-sato,

I am using following configuration:

```yml
in:
  type: oracle
  driver_path: /ojdbc7-12.1.0.2.jar
  url: jdbc:oracle:thin:@something.com:1526/DB
  user: user
  password: "password"
  query: "SELECT * SCHEMA.TABLE"
  fetch_rows: 4000
  connect_timeout: 100
out:
   type: bigquery
   mode: replace
   auth_method: service_account
   project: project
   dataset: "dataset"
   table: "table"
   location: europe-west2
   json_keyfile: credentials.json
```
