### ISSUE TITLE
Embulk freezes when I specify where condition

### ISSUE THREAD

**Issue by OmkarPathak** [embulk/embulk-input-jdbc#177]
Hi team,

I am using `embulk-input-oracle` for fetching data. This works fine when I write query without any `WHERE` clause. But when I specify a WHERE clause it just freezes.

This is the config we are using:

```yml
in:
  type: oracle
  driver_path: ojdbc7-12.1.0.2.jar
  url: jdbc:oracle:thin:@something.com:1526/DB
  user: ABC
  password: "PASSWORD"
  query: "SELECT * FROM SCHEMA.TABLE WHERE ABC_DATE > to_date('01 JAN 2019','DD MON YY')"
  fetch_rows: 20000
  connect_timeout: 100
```
