### ISSUE TITLE
date type between mssql and mysql not working.

### ISSUE THREAD

**Issue by makkaba** [embulk/embulk-input-jdbc#186]
[situation]
(MSSQL)
nullable *date* type 
-> 
(MYSQL)
nullable date type

[issue]
destination date columns are filled with NULL value. 
even all the source columns have values.

``` yaml
in:
  type: sqlserver
  host: ***
  user: ***
  password: ***
  database: ***
  query: |-
    SELECT
      [sdate],
   ***
    FROM *** WITH (NOLOCK)
out:
  type: mysql
  host: ***
  user: ***
  password:***
  database: ***
  table: ***
  mode: merge_direct
  options: {useUnicode: true, characterEncoding: UTF-8}
  column_options:
    sdate: {type: date null}

```

**Comment by hiroyuki-sato** [comment]
Hello, @makkaba 


* Could you double-check whether `sdata` contains NULL value?
* Does your table has primary or unique constraints?
* Could you tell us more detail about the problem? (What kind of data did you insert and update?)


I tested merge_direct feature in the following environment.
It seems worked well.

* OS: macOS 10.15
* MySQL: 8.0.19
* Embulk: embulk 0.9.23
* embulk-output-mysql: 0.8.7

```yaml
in:
  type: inline
  schema:
    - { name: id, type: long }
    - { name: string_column, type: string }
    - { name: double_column, type: double }
    - { name: boolean_column, type: boolean }
    - { name: sdate, type: timestamp }
  data:

    # First data insertion.
    - { id: 1, string_column: test, double_column: 0.1, boolean_column: true, sdate: '2016-06-14 15:19:05' }
    - { id: 2, string_column: test, double_column: 0.1, boolean_column: true, sdate: '2016-06-14 15:19:05' }
    - { id: 3 }

    # 2nd data insertion
    #- { id: 1, string_column: test, double_column: 0.1, boolean_column: true, sdate: '2016-06-14 15:19:05' }
    #- { id: 2, string_column: test, double_column: 0.1, boolean_column: true }
    #- { id: 3, string_column: test, double_column: 0.1, boolean_column: true, sdate: '2016-06-14 15:19:05' }
#out: {type: stdout}
out:
  type: mysql
  host: localhost
  user: user
  password: password
  database: embulk_test
  table: merge_direct_test
  mode: merge_direct
  options: {useUnicode: true, characterEncoding: UTF-8}
  create_table_constraint: 'primary key(id)'
  column_options:
    purchase: {type: date null}

```


## first insert results.

```
show fields from merge_direct_test;
+----------------+------------+------+-----+---------+-------+
| Field          | Type       | Null | Key | Default | Extra |
+----------------+------------+------+-----+---------+-------+
| id             | bigint     | NO   | PRI | NULL    |       |
| string_column  | text       | YES  |     | NULL    |       |
| double_column  | double     | YES  |     | NULL    |       |
| boolean_column | tinyint(1) | YES  |     | NULL    |       |
| sdate          | timestamp  | YES  |     | NULL    |       |
+----------------+------------+------+-----+---------+-------+
5 rows in set (0.00 sec)
```

```
select * from merge_direct_test;
+----+---------------+---------------+----------------+---------------------+
| id | string_column | double_column | boolean_column | sdate               |
+----+---------------+---------------+----------------+---------------------+
|  1 | test          |           0.1 |              1 | 2016-06-14 15:19:05 |
|  2 | test          |           0.1 |              1 | 2016-06-14 15:19:05 |
|  3 | NULL          |          NULL |           NULL | NULL                |
+----+---------------+---------------+----------------+---------------------+
3 rows in set (0.00 sec)
```

## 2nd data insert.

* I expect update the following
  * id 3 sdata: NULL -> '2016-06-14 15:19:05'
  * id 2 sdata: 2016-06-14 15:19:05 -> NULL

```
mysql> select * from merge_direct_test;
+----+---------------+---------------+----------------+---------------------+
| id | string_column | double_column | boolean_column | sdate               |
+----+---------------+---------------+----------------+---------------------+
|  1 | test          |           0.1 |              1 | 2016-06-14 15:19:05 |
|  2 | test          |           0.1 |              1 | NULL                |
|  3 | test          |           0.1 |              1 | 2016-06-14 15:19:05 |
+----+---------------+---------------+----------------+---------------------+
3 rows in set (0.00 sec)
```

**Comment by makkaba** [comment]
@hiroyuki-sato
Thank you for testing! 
but something is different. 
in my case, the type is not timestamp. 
yyyy-MM-dd style"date"  type.

**Comment by hiroyuki-sato** [comment]
Hello, @makkaba 

It worked too. The following test used `date` column.

[test script](https://github.com/hiroyuki-sato/embulk-support/blob/master/20200612_output-mysql-merge_direct/config.yml)

## First insert

After insert

```
mysql> show fields from merge_direct_test;
+----------------+------------+------+-----+---------+-------+
| Field          | Type       | Null | Key | Default | Extra |
+----------------+------------+------+-----+---------+-------+
| id             | bigint     | NO   | PRI | NULL    |       |
| string_column  | text       | YES  |     | NULL    |       |
| double_column  | double     | YES  |     | NULL    |       |
| boolean_column | tinyint(1) | YES  |     | NULL    |       |
| sdate          | date       | YES  |     | NULL    |       |
+----------------+------------+------+-----+---------+-------+
5 rows in set (0.00 sec)
```

```
mysql> select * from merge_direct_test;
+----+---------------+---------------+----------------+------------+
| id | string_column | double_column | boolean_column | sdate      |
+----+---------------+---------------+----------------+------------+
|  1 | test          |           0.1 |              1 | 2016-06-14 |
|  2 | test          |           0.1 |              1 | 2016-06-14 |
|  3 | NULL          |          NULL |           NULL | NULL       |
+----+---------------+---------------+----------------+------------+
3 rows in set (0.00 sec)
```

## 2nd insert

After update.

I expect to update the following
* id 2 sdata: `2016-06-14` -> `NULL`
* id 3 sdata: `NULL` -> `2016-06-14`

```
mysql> select * from merge_direct_test;
+----+---------------+---------------+----------------+------------+
| id | string_column | double_column | boolean_column | sdate      |
+----+---------------+---------------+----------------+------------+
|  1 | test          |           0.1 |              1 | 2016-06-14 |
|  2 | test          |           0.1 |              1 | NULL       |
|  3 | test          |           0.1 |              1 | 2016-06-14 |
+----+---------------+---------------+----------------+------------+
3 rows in set (0.00 sec)
```

**Comment by makkaba** [comment]
@hiroyuki-sato 
thank you for research.

I have realized something new. 

In amazon linux ubuntu, it works properly. (it means date value is inserted)

But in WSL(Window Subsystem Linux) Ubuntu in my local window machine, 
all the date values are filled with NULL. 

It can be WSL problem itself. or some environment problem
ex) timezone ..

Is there any factor which affects to convert date type?

**Comment by hiroyuki-sato** [comment]
Hello, @makkaba 

Did you check consistency in both environments?
Does WSL environment have primary or unique consistency?

Have you ever executed my test script in your WSL environment?
If so, could you tell me the result?

**Comment by makkaba** [comment]
@hiroyuki-sato 


# test1
i have tested your test script in WSL environment.
(timestamp -> date)
## result  
sdate field is filled with NULL value.

# test2
chaging the type of sdate with 'date' 
```
in:
  type: inline
  schema:
    - { name: id, type: long }
    - { name: string_column, type: string }
    - { name: double_column, type: double }
    - { name: boolean_column, type: boolean }
    - { name: sdate, type: date }
  data:

    # First data insertion.
    - { id: 1, string_column: test, double_column: 0.1, boolean_column: true, sdate: '2016-06-14' }
    - { id: 2, string_column: test, double_column: 0.1, boolean_column: true, sdate: '2016-06-14' }
    - { id: 3 }

```

## result

```
org.embulk.exec.PartialExecutionException: org.jruby.exceptions.RaiseException: (RuntimeError) Unknown type :date
        at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(BulkLoader.java:340)
        at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:566)
        at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:35)
        at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:353)
        at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:350)
        at org.embulk.spi.Exec.doWith(Exec.java:22)
        at org.embulk.exec.BulkLoader.run(BulkLoader.java:350)
        at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:242)
        at org.embulk.EmbulkRunner.runInternal(EmbulkRunner.java:291)
        at org.embulk.EmbulkRunner.run(EmbulkRunner.java:155)
        at org.embulk.cli.EmbulkRun.runSubcommand(EmbulkRun.java:431)
        at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:90)
        at org.embulk.cli.Main.main(Main.java:64)
        Suppressed: java.lang.NullPointerException
                at org.embulk.exec.BulkLoader.doCleanup(BulkLoader.java:463)
                at org.embulk.exec.BulkLoader$3.run(BulkLoader.java:397)
                at org.embulk.exec.BulkLoader$3.run(BulkLoader.java:394)
                at org.embulk.spi.Exec.doWith(Exec.java:22)
                at org.embulk.exec.BulkLoader.cleanup(BulkLoader.java:394)
                at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:245)
                ... 5 more
Caused by: org.jruby.exceptions.RaiseException: (RuntimeError) Unknown type :date
        at RUBY.block in initialize(uri:classloader:/gems/embulk-0.9.23-java/lib/embulk/schema.rb:46)
        at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1735)
        at RUBY.initialize(uri:classloader:/gems/embulk-0.9.23-java/lib/embulk/schema.rb:20)
        at RUBY.block in transaction(uri:classloader:/gems/embulk-0.9.23-java/lib/embulk/input_plugin.rb:60)
        at RUBY.resume(/home/ubuntu/.embulk/lib/gems/gems/embulk-input-inline-0.1.0/lib/embulk/input/inline.rb:21)
        at RUBY.transaction(/home/ubuntu/.embulk/lib/gems/gems/embulk-input-inline-0.1.0/lib/embulk/input/inline.rb:17)
        at RUBY.transaction(uri:classloader:/gems/embulk-0.9.23-java/lib/embulk/input_plugin.rb:58)

Error: org.jruby.exceptions.RaiseException: (RuntimeError) Unknown type :date
```
