### ISSUE TITLE
Binary data cannot be copied with Embulk

### ISSUE THREAD

**Issue by koichi-oshima** [embulk/embulk-input-jdbc#217]
I want to copy RDS to RDS with embulk, but it seems that binary data is not supported and I get an error.
As you can see in the error message, adding DATA: {value_type: string} did not resolve it.

If you know any workaround, please let me know. ..

## error

```
Caused by: java.lang.UnsupportedOperationException: Unsupported type MEDIUMBLOB (sqlType=-4) of '<column name>' column. Please add 'DATA: {value_type: string}' to 'column_options: {...}' option to convert the values to strings, or exclude the column from 'select:' option
```

## settings
- _input.yml.liquid

```
in:
  type: mysql
  host: {{ env.IN_MYSQL_HOST }}
  user: {{ env.IN_MYSQL_USER }}
  password: {{ env.IN_MYSQL_PASSWORD }}
  database: dbA
  select: "*"
  options: {useLegacyDatetimeCode: false, serverTimezone: Asia/Tokyo}
```

- _output.yml.liquid

```
out:
  type: mysql
  mode: replace
  host: {{ env.OUT_MYSQL_HOST }}
  user: {{ env.OUT_MYSQL_USER }}
  password: {{ env.OUT_MYSQL_PASSWORD }}
  database: dbA
  select: "*"
```

- config.yml.liquid

In the following cases, I get the above error.
```
{% include 'input' %}
  table: tableA
{% include 'output' %}
  table: tableA
  column_options:
    columnA: {value_type: string}
```

In the following cases, A temporary table is created and no error is displayed, but it remains frozen and does not exit.
```
{% include 'input' %}
  table: tableA
  columnA: {value_type: string}
{% include 'output' %}
  table: tableA
  column_options:
```

## table
ID:INT
DATA:MEDIUMBLOB
CREATED_DATE:DATETIME
UPDATED_DATE:DATETIME

## version
Amazon linux2
Embulk v0.9.23
embulk-input-mysql 0.10.1
embulk-output-mysql 0.8.7

**Comment by hiroyuki-sato** [comment]
I answered the same question in [teratail](https://teratail.com/questions/343563#reply-472679) (It's kind of Japanese Stack Overflow)

Below is the summary.

Embulk doesn't support binary columns. You need to convert it to non-binary using base64 or something.

```sql
create table strtest(str1 varbinary(20), str2 char(5) character set utf8);
insert into strtest values('空', '空'); -- 空 is NULL in Japanese. binary example.
```

```yaml
in:
  type: mysql
  user: user
  password: password
  database: database
  table: strtest
  host: host
  select: TO_BASE64(str1),str2
out:
  type: stdout
```

And You can get the following result. You can decode like the `echo "56m6" | openssl base64 -d`

```
56m6,空
```
