### ISSUE TITLE
Problem with MySQL TINYINT(1) type

### ISSUE THREAD

**Issue by lance-edmodo** [embulk/embulk-input-jdbc#53]
Hi-

We have a table with a field of type TINYINT(1). This means a 1-byte number from -128 to 127 that should be printed with only 1 digit wide.  When we read this field from Embulk, it is interpreted to be boolean. 0 is false and all non-zero values are true.

In order to load this correctly, I have to work around MYSQL type propagation. I had to fool MySQL into raising the field to a regular int with this query:

select * from (select * from table where true UNION select * from table where false) x

This causes MySQL to change the field to an int inside the query, and return the field as an int instead of a boolean.

**Comment by hiroyuki-sato** [comment]
@lance-edmodo 

Have you ever tried column_options settings?

For example

```yaml
in:
  type: mysql
  select: "col1, col2, col3"
  column_options:
    col1: {type: long}
```
